name: Build

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.2.0
        with:
          python_ver: '3.8'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'PyMonitor'